### ISSUE TITLE
Limitation on multiple relations of the same type

### ISSUE THREAD

**Issue by atomate** [toopay/gas-orm#10]
Hi there, here is an issue I discovered while trying to setup an object with more than one 'has_one' relationship

`public $relations = array(
        'belongs_to' => array('category' => array('foreign_id' => 'category_id')),
        'has_one' => array('site' => array('foreign_id' => 'site_id')),
        'has_one' => array('locale' => array('foreign_id' => 'locale_id')),
);`

Due to the nature of php arrays, keys seem to like to be unique.

hope this helps

**Comment by toopay** [comment]
You were misunderstood about Gas convention. Above syntax should be something like below instead : 

```
public $relations = array(
    'belongs_to' => array('category' => array('foreign_id' => 'category_id')),
    'has_one' => array(
        'site' => array('foreign_id' => 'site_id'), 
        'locale' => array('foreign_id' => 'locale_id'),
    )
);
```

**Comment by atomate** [comment]
yes, you're right, my bad.
