### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by flashover** [toopay/gas-orm#15]
Hi,

Why isn't the documentation included with the source?

I'd like to have it available offline (and make improvements).

Grtz,

**Comment by toopay** [comment]
For now, the documentation is on Sphinx format and it is available on : https://github.com/toopay/gas-orm/tree/doc 

if you found some typo or you planning to adding some usefull information (which not provided by the original documentation yet), just fetch from the upstream and edit those rst files. I'd happy to merge any pull request that doing any improvement over it.
