### ISSUE TITLE
Self referential data

### ISSUE THREAD

**Issue by tikiatua** [toopay/gas-orm#18]
Unfortunately, I cannot get self referential relationships to work:

Relationship defined as 
   "based_on" = ORM::self();

Results in the following error: 
  Model \Model\Variable located, but missing relationship properties.

Looking at the code in core.php -> generate_identifier() the self referential relationship seems not to be implemented yet.

But thanks for the nice work anyway,
Tikiatua

**Comment by toopay** [comment]
I'd opened #6 for this one. Until that one finished developed, you can do some workaround using any available finder method(s).

**Comment by tikiatua** [comment]
Ok. Thank you.
