### ISSUE TITLE
Query Constraints Are Being Cached

### ISSUE THREAD

**Issue by RLovelett** [toopay/gas-orm#26]
In the following snippit:

``` php
class ItemGas extends ORM {

  // boilerplate

  private function getCriteria() {
    return ItemGas::where("parentId = {$this->id} AND itemType = 'criterion'")->all();
  }

  private function highestScoredAlternative() {
    return ItemGas::find(689);
  }

}
```

if I call `highestScoredAlternative` before `getCriteria` then the SQL used to run the `getCriteria` command looks like:

``` sql
SELECT *
FROM (`items`)
WHERE `id` IN (689) 
AND `parentId` = 585 AND itemType = 'criterion'
```

How does 1 affect the other? What should I do to prevent the `WHERE id IN (689)` part?

**Comment by toopay** [comment]
It seems you calling the same Model twice in object context. In short, if you calls above methods sequencetially, with first call to `highestScoredAlternative` then you call `getCriteria`, you eventually get bellow result : 

```
$highestScored = $this->highestScoredAlternative();
// Now, if you dump out its recorder :
var_dump($this->recorder);
// You most likely would have :
//class Gas\Data#19 (1) {
//  private $collections =>
//  array(2) {
//    'where_in' =>
//    array(2) {
//      [0] =>
//      string(2) "id"
//      [1] =>
//      array(1) {
//        ...
//     }
//    }
//    'get' =>
//    array(1) {
//      [0] =>
//      string(4) "user"
//    }
//  }
//}

// If you calling second method
$criteria = $this->getCriteria();
// Now, if you dump out its recorder :
var_dump($this->recorder);
// You most likely have :
//class Gas\Data#19 (1) {
//  private $collections =>
//  array(2) {
//    'where_in' =>
//    array(2) {
//      [0] =>
//      string(2) "id"
//      [1] =>
//      array(1) {
//        ...
//     }
//    }
//    'get' =>
//    array(1) {
//      [0] =>
//      string(4) "user"
//    }
//   'where' =>
//    array(1) {
//      [0] =>
//      string(16) "parentId = {$this->id} AND itemType = 'criterion'"
//    }
//  }
//}
```

You were actually appending more stack, into same model object recorder.

## SOLUTION

Isolate each model process : 

```
class ItemGas extends ORM {

  // boilerplate

  private function getCriteria() {
    return ItemGas::make()->where("parentId = {$this->id} AND itemType = 'criterion'")->all();
  }

  private function highestScoredAlternative() {
    return ItemGas::make()->find(689);
  }

}
```

**Comment by RLovelett** [comment]
So I tried the solution and it of course works, seriously, thank you for that!

I guess I have a fundamentally flawed expectation of what the GasORM framework is doing here. I assumed that the reference to `ItemGas` was a static reference, thus, would be independent from one reference to another.

Also, what is the `ItemGas::make` call _making_ exactly?

**Comment by toopay** [comment]
@RLovelett It was a static reference, but you calling them from object context. Beside above solution, another solution is to change `getCriteria` and `highestScoredAlternative` into static function, then it would be independent from one reference to another without the need to adding `make` on each functions. `make` is a factory method.
