### ISSUE TITLE
Codeigniter 3: can not find Model\User

### ISSUE THREAD

**Issue by aaami1ster** [toopay/gas-orm#37]
I use gas-orm with codeginter 3.03. 
I changed all classes to uppercase (such as gas.php to Gas.php and so on) to comply with naming convention of ci3
the gas-orm works well in windows (using wamp) and in mac (using mamp).
but it fails to work in ubuntu 14.04 (using lamp) with following error

`can not find class Model\User`

even if the User.php model class is uppercase

any help pleasse

**Comment by skoshkarev** [comment]
@aaami1ster is there any news on this issue?

**Comment by aaami1ster** [comment]
**YES I fix this problem.**
the problem is in namespace name 'Model'. you can either 
1. change namespace 'Model' to lower case 'model' in all files
2. or do the following steps

### first step:

in third_pary/gas/classes/Core.php (line 761) remove strtolower function (so will use the exact name of class and model)

### second step:

in Core.php replace all `$path['model']` with `$path['Model']`

this works for me

**Comment by HasanCse** [comment]
Not working for me. Couldn't find anything to do second step
