### ISSUE TITLE
error in models with postgresql db

### ISSUE THREAD

**Issue by rshsdev** [toopay/gas-orm#4]
I dont know if this was an issue but im getting warning message in line 3426

3426  if (self::$default_datatypes[$field_gas_type] != $field_raw_type)

warning: undefined index.

My primary key is id with int4 datatype. All my model is generated by GAS, so i don't know why i'm getting this warning message.

PS: In mysql, Gas is working fine, i didnt get this warning message. 
Thanks for this awesome ORM, one of the best that i've tested.

**Comment by toopay** [comment]
Hey, reith2004.

Yes, auto migration is experimental feature. It perfectly fine with MySQL, because i has defined all possible datatypes into Gas_janitor dictionary, and...not yet with Postgre. I has put small "TODO" note on related line you pointed, and will add this fix in my upcoming commit. I will include the commit detail, if i done with this.

**Comment by rshsdev** [comment]
wow thanks, fast reply... 

also line 3193 gives me warning messages, gas-orm v4.1.1,
heres the warning message, 
ucfirst() expects parameter 1 to be string, array given

its quite obvious i guess, ucfirst, $model seems to be empty or $model is an arrays,
and its all also create a migration with the filename 001_Array.php, 002_Array.php,

Edit: I love this feature :) it seems broke in v4.1.1, its working v4.1

that warning message comes when the auto_create_models = true..

**Comment by toopay** [comment]
`that warning message comes when the auto_create_models = true`
This commit , 93c09182be4dd1f5a7c07106267c66ed599233c5, (actually just forgot to rename some variable) fix that. Can you confirm afterward.

**Comment by rshsdev** [comment]
Nice doc,.. its perfectly working now, should I close the issue now or wait for postgre fix? I using it now, and i can say, its really really great... for ten and thousands of records its really fast, need to do some benchmarks ;) Thanks for the fast reply.. Gotta explore this great ORM... :)

-Burned to the core but not broken-
-----Original Message-----

**Comment by toopay** [comment]
Leave it open. I will close this, if i fix those datatypes thingy, alongside with other databases, later in my upcoming free time.

UPDATE :
this commit 703a34e5732c12d3a88ac0abdc9bdcc6cb9ffd66 fix this.
